"""
Report Assembler Node
Merges Writer draft + Verifier results into a final polished report.
Adds: confidence indicators per section, citation summary, and metadata header.
"""

import re
import time
import logging
from datetime import datetime
from agents.state import VerityState
from agents.audit_logger import AuditLogger
from config import settings

logger = logging.getLogger(__name__)

SECTION_ORDER = [
    "Executive Summary",
    "Company Overview",
    "Financial Performance",
    "Market Valuation",
    "Recent Developments",
    "Bull Case",
    "Bear Case",
    "Key Risks",
    "Investment Thesis",
]


def assembler_node(state: VerityState) -> VerityState:
    """
    LangGraph node: Report Assembler.
    Produces the final polished report with confidence scores per section.
    """
    start = time.monotonic()
    ticker = state["ticker"]
    run_id = state["run_id"]
    audit = AuditLogger(settings.audit_log_dir, run_id)

    draft = state.get("draft_report", "")
    citations = state.get("citations", [])
    unverified = state.get("unverified_claims", [])
    market_data = state.get("market_data", {})
    financial_ratios = state.get("financial_ratios", {})
    company_name = state.get("company_name", ticker)

    # ── Compute per-section confidence ────────────────────────────────────────
    confidence_by_section = _compute_section_confidence(draft, citations)

    # ── Build final report ────────────────────────────────────────────────────
    verified_count = sum(1 for c in citations if c.get("verified"))
    total_count = len(citations)
    citation_coverage = (verified_count / total_count * 100) if total_count > 0 else 0.0

    header = _build_header(
        company_name=company_name,
        ticker=ticker,
        run_id=run_id,
        verified_count=verified_count,
        total_count=total_count,
        citation_coverage=citation_coverage,
        unverified_count=len(unverified),
        market_data=market_data,
        financial_ratios=financial_ratios,
    )

    # Clean up citation markers for display
    clean_report = _render_citations(draft)

    # Append citation index
    citation_index = _build_citation_index(citations)

    # Append disclaimer
    disclaimer = (
        "\n\n---\n"
        "> **Disclaimer:** This report is generated by an automated AI research system (Verity) "
        "for portfolio/educational purposes only. It is not financial advice. "
        "All factual claims are traced to retrieved source documents. "
        f"Citation coverage: {citation_coverage:.0f}% ({verified_count}/{total_count} claims verified). "
        "Verify all data independently before making investment decisions."
    )

    final_report = header + "\n\n" + clean_report + citation_index + disclaimer

    duration = time.monotonic() - start
    trace_entry = audit.log(
        node="assembler",
        inputs={"draft_length": len(draft), "citations": total_count},
        outputs={
            "final_report_length": len(final_report),
            "citation_coverage_pct": round(citation_coverage, 1),
            "verified": verified_count,
            "unverified": len(unverified),
        },
        tool_calls=[],
        duration_seconds=duration,
    )

    return {
        **state,
        "final_report": final_report,
        "confidence_by_section": confidence_by_section,
        "trace": state.get("trace", []) + [trace_entry],
    }


def _build_header(
    company_name: str,
    ticker: str,
    run_id: str,
    verified_count: int,
    total_count: int,
    citation_coverage: float,
    unverified_count: int,
    market_data: dict,
    financial_ratios: dict,
) -> str:
    price = market_data.get("current_price", "N/A")
    market_cap = market_data.get("market_cap") or 0
    sector = market_data.get("sector", "N/A")
    pe = market_data.get("pe_ratio", "N/A")

    coverage_emoji = "🟢" if citation_coverage >= 80 else "🟡" if citation_coverage >= 60 else "🔴"

    header = f"""# {company_name} ({ticker}) — Equity Research Report

> **Generated by Verity** | Run ID: `{run_id}` | {datetime.now().strftime("%B %d, %Y")}
> {coverage_emoji} **Citation Coverage: {citation_coverage:.0f}%** ({verified_count}/{total_count} claims verified)
> ⚠️ {unverified_count} claim(s) could not be verified against source documents

| | |
|---|---|
| **Current Price** | ${price} |
| **Market Cap** | ${market_cap:,.0f} |
| **Sector** | {sector} |
| **P/E Ratio** | {pe} |
| **Report Date** | {datetime.now().strftime("%Y-%m-%d")} |
"""
    return header


def _render_citations(text: str) -> str:
    """
    Replace [[CITE: source | passage]] markers with readable inline citation format.
    E.g.: [¹ 10-K FY2024]
    """
    counter = [0]
    citation_map = {}

    def replace(match):
        counter[0] += 1
        source = match.group(1).split("|")[0].strip()
        citation_map[counter[0]] = source
        return f"[^{counter[0]}]"

    rendered = re.sub(r'\[\[CITE:(.*?)\]\]', replace, text, flags=re.DOTALL)
    return rendered


def _build_citation_index(citations: list[dict]) -> str:
    """Build a numbered citation reference list at the bottom of the report."""
    if not citations:
        return ""

    lines = ["\n\n---\n## Citations\n"]
    for i, c in enumerate(citations, 1):
        status = "✅" if c.get("verified") else "❌ [UNVERIFIED]"
        confidence = c.get("confidence", 0.0)
        source = c.get("source", "Unknown source")
        passage = c.get("passage", "")[:200]
        lines.append(
            f"{i}. {status} **{source}** (confidence: {confidence:.0%})\n"
            f"   > {passage}\n"
        )
    return "\n".join(lines)


def _compute_section_confidence(report: str, citations: list[dict]) -> dict[str, float]:
    """
    Estimate confidence per report section based on citation verification rate
    in that section's text window.
    """
    confidence = {}
    for section in SECTION_ORDER:
        # Find section in report (rough heuristic)
        pattern = rf"## {re.escape(section)}(.*?)(?=## |\Z)"
        match = re.search(pattern, report, re.DOTALL | re.IGNORECASE)
        if not match:
            continue
        section_text = match.group(1)
        # Count citations in this section
        cites_in_section = re.findall(r'\[\[CITE:.*?\]\]', section_text, re.DOTALL)
        if not cites_in_section:
            confidence[section] = 0.5  # no citations = uncertain
            continue
        # Find matching citations and compute average confidence
        n = len(cites_in_section)
        avg = 0.7  # default if we can't match precisely
        if citations:
            relevant = citations[:n]
            avg = sum(c.get("confidence", 0.5) for c in relevant) / len(relevant)
        confidence[section] = round(avg, 2)
    return confidence
